config: 
  info:  "master branch,springcloud-config/config-dev.yml version=7"
server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**

        - id: payment_route2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
#  #############################新增网关配置###########################
#  cloud:
#    gateway:
#      routes:
#        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
#
#        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
#####################################################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

#
#eureka:
#  instance:
#    hostname: cloud-gateway-service
#  client:
#    #表示是否将自己注册进EurekaServer默认为true。
#    register-with-eureka: true
#    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetchRegistry: true
#    service-url:
#      #单机
#      #      defaultZone: http://localhost:7001/eureka
#      # 集群
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
